# server:
#   port: 8080
#   servlet:
#     context-path: /

# spring:
#   datasource:
#     driver-class-name: com.mysql.cj.jdbc.Driver
#     url: jdbc:mysql://10.64.33.11:3306/hr_manager?characterEncoding=utf8&autoReconnect=true&useSSL=false
#     username: root
#     password: mysql

server:
  port: 8080
  servlet:
    context-path: /

spring:
  datasource:
    url: jdbc:mysql://10.64.33.11:3306/hr_manager?useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&failOverReadOnly=false&serverTimezone=GMT%2B8
    username: root
    password: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always



    hikari:
      auto-commit: true
      connection-timeout: 10000
      idle-timeout: 30000
      maximum-pool-size: 15
      minimum-idle: 5